name: First Workflow
on: push

jobs:
  job-1:
    runs-on: ubuntu-24.04
    steps:
      - name: print hello all
        run: echo "hello all"

      - name: print cpu infro
        run: lscpu

      - name: print mem info
        run: lsmem

      - name: print volume
        run: lsblk
