name: project2
on: push

jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
      - name: get code
        uses: actions/checkout@v7

      - name: set up nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 24

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Build
        run: npm run build

      - name: deploy
        run: echo "deploying server.."
